---
title: "Grades analysis"
author: "Théo Claverotte dit Laprima"
format: html
echo: false
message: false
warning: false
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(here)
library(vroom)
library(stringr)
here::i_am("r-101-grade-analysis.Rproj")
```

## Question 1

```{r}
grades<-vroom(here("grades.csv"))
grades |> summarise(anyNA(Exam))
is.na(c(1, 2, NA, 4, NA))
```

## Question 2

```{r}
data_exam<-grades %>%
  summarise(mean(Exam, na.rm = TRUE), min(Exam, na.rm = TRUE), max(Exam,na.rm = TRUE), median(Exam, na.rm = TRUE), n())
library(knitr)
knitr::kable(data_exam)
```

## Question 3

```{r}
NA_exam <- grades %>%
  filter(is.na(Exam)) %>%
  count(is.na(Exam)) 
print(NA_exam)
```

the number of students who have not pass the Exam is `r NA_exam`.

## Question 4

```{r}
grades_without_na<-grades %>%
  filter(!is.na(Exam))
print(grades_without_na)
  
ggplot(grades_without_na, aes(x = Exam)) + geom_histogram(binwidth = 0.7, fill="darkorange")

```

## Question 5

```{r}
student_by_grp <- grades %>% 
  group_by(Group) %>%
  summarise(n())
print(student_by_grp)
  
```

## Question 6

```{r}

ggplot(grades, aes(x = Group, fill= Group)) + geom_bar() 
```

## Question 7

```{r}
ggplot(grades_without_na, aes(x = Group, y = Exam, fill = Group)) + geom_boxplot()
```

## Question 8

```{r}
missed_exam <- grades %>%
  group_by(Group) %>%
  summarise(Missed_Exam = sum(is.na(Exam)))

missed_exam_2 <- table(grades$Group, is.na(grades$Exam))

missed_exam_2 <- as.data.frame(missed_exam)
colnames(missed_exam_2) <- c("Group", "Missed_Exam")

knitr::kable(missed_exam)

```

## Question 9

```{r}
ggplot(missed_exam, aes(x = Group, y = Missed_Exam)) +
  geom_col() 
```

## Question 10 
```{r}
df_long_format_grades <- grades %>%
  pivot_longer(
    cols = -c(Id, Group), names_to = "name", values_to = "value"
  )

df_long_format_grades
```

## Question 11
```{r}
missing_grades_by_student <- df_long_format_grades %>%
  group_by(Id) %>%
  summarise(missing_grades_by_student = sum(is.na(value)))

missing_grades_by_student
```

## Question 12
```{r}
ggplot(missing_grades_by_student, aes(x = missing_grades_by_student)) +
  geom_histogram(binwidth = 1, fill = "lightgreen", color = "black") +
  labs(title = "Distribution of Total Missing Grades per Student", x = "Number of Missing Grades", y = "Frequency")
```

## Question 13 

```{r}
missing_student <- df_long_format_grades %>%
  filter(name== "Exam") %>%
  group_by(Group) %>%
  summarise(missing_student = sum(is.na(value)))


knitr::kable(missing_student)

```

## Question 14
```{r}
online_exam_na <- df_long_format_grades %>%
  filter(str_starts(name, "Online_MCQ")) %>%
  group_by(Id) %>%
  summarise(online_exam_na = sum(is.na(value)))
online_exam_na
```

## Question 15


```{r}

grades_na<-grades%>%
  rowwise()%>%
  mutate(NA_count=sum(is.na(c_across(starts_with("Online")))))
  
grades_by_na_online<-grades_na %>%
  group_by(NA_count) %>%
  summarise(mean=mean(Exam,na.rm=TRUE))

ggplot(grades_by_na_online,aes(x=NA_count,y=mean), )+
  geom_col()+
  labs(title="the distribution of the grades at the Exam conditioned by the number of missing grades for the online tests",
       x="online tests missed",
       y="Grades out of 20")
  
```
## Question 16
```{r}
missed_any_grade <- df_long_format_grades %>%
  filter(str_starts(name, "MCQ")) %>%
  group_by(Id) %>%
  summarise(Missed = any(is.na(value)))
missed_any_grade
```

## Question 17


```{r}
percentage_missed_per_group <- missed_any_grade %>%
  inner_join(df_long_format_grades, by = "Id") %>%
  group_by(Group) %>%
  summarise(P_missed = mean(Missed)*100)

percentage_missed_per_group

```

## Question 18

```{r}
mean_by_group<-grades|>
  group_by(Group)|>
  summarise(mean=mean(Exam,na.rm=TRUE))

Exam_missed_and_mean<-inner_join(percentage_missed_per_group,mean_by_group,by="Group") %>%
  ggplot(aes(x=P_missed,y=mean,fill=Group))+
  geom_hex()+
  labs(title="Every group's average grade at the Exam according to the percentage of missed MCQ gradse",
       x="Percentage of students who missed at least one MCQ",
       y="Average grade to the final exam")
Exam_missed_and_mean
```


